name: Publish PyPI
on:
  create:
    tags:
      - v*.*.*
jobs:
  build-and-publish:
    name: Build and publish Python 🐍 distributions 📦 to PyPI
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
          architecture: x64

      - name: Intall build tools
        run: pip install --upgrade setuptools wheel twine

      - name: Checkout code
        uses: actions/checkout@v1

      - name: Build source distribution
        run: python setup.py sdist bdist_wheel

      - name: Upload the package to PyPI via Twine
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TWINE_USERNAME }}
        run: twine upload dist/*
